all:
    hosts:
        publicec2:
            ansible_host : <IPADDRESS_HERE> 
    vars:
        ansible_user : ubuntu
        ansible_ssh_private_key_file: <PRIVATE_KEY_PATH_HERE> 
        ansible_become : yes 
#        ansible_become_user : root

    children:
        publicservers :
            hosts:
                publicec2:

