---

- hosts: publicec2
  tasks:
    - name : Install Figlet
      become : yes
      apt : 
          name : figlet
          state : present

    - name : Install python3 and python-docker
      become : yes
      apt : 
          name : ['python3', 'python3-pip', 'docker.io'] 
          state : present

    - name : Install python docker
      pip:
          name : docker 

    - name : Run pyserver
      docker_container: 
          name : quotepyserver
          image : sswamin729/quotepyserver:1.0
          state : started
          published_ports : 
              - 8000:8000
          recreate : yes
